### ISSUE TITLE
Hide Already Installed Mods, and Fabric Mods in Forge Mod Download

### ISSUE THREAD

**Issue by GamingInfinite** [killpowa/Twickt-Launcher#1085]
This isn't really related to a problem, but just a way to hide already installed mods, and also hide mods that have no version for your instance (eg. Fabric Mods that Show Up in Forge Area).

**Comment by Eskaan** [comment]
Fabric ones in Forge and otherwise should be removed by a CurseForge API change and already installed mods showing up is on purpose because you might want to change the version of it. The duplicate problem shouldn’t be much of a problem anyways. (Also this would drastically reduce performance to first check for ~200 Mods from a Modpack.)
