### ISSUE TITLE
Hanging on Forge download on reinstall

### ISSUE THREAD

**Issue by Nezmin2** [killpowa/Twickt-Launcher#1092]
**Describe the bug**
After playing ATM7 .15 for a couple of days, the server upgraded to .16. I tried to start a new instance with the new version, but the launcher hung at the Forge install. I have verified my Java install and links.

**To Reproduce**
1. Go to 'Add Instance'
2. Click on 'Import Zip'
3. Click on 'Browse'
3. Select file 'All+the+Mods+7-0.0.16.zip'
4. Click on 'Open'
5. Click 'Arrow'
6. Click 'Arrow'

**Expected behavior**
Install loads game files, but hangs on Forge install.

**Possible solutions**
Unknown

**Screensh
![ForgeHanging](https://user-images.githubusercontent.com/20376159/135706656-ce859056-2885-4ee6-a587-1b4799ac25c9.png)
ots**

**Operating System:**
- OS: [PopOS]
- Version: [21.04]
- Java Version: [8/16]
- Minecraft Version: [e.g. 1.17.1.16]
- Mod Loader: [e.g. Forge]

**Additional context**
![GDLauncherlog](https://user-images.githubusercontent.com/20376159/135706713-fdab8414-778b-42fd-8d5a-69ae294497d8.png)

**Comment by e30Birdy** [comment]
I have the same issue just trying to install FTB OceanBlock at the moment. I have tried 4 times now and it just gets stuck and does nothing. 

Edit: Tried 1.1.15 beta 5 and seems to be working. Looks like 1.1.14 is not working right. Downloaded everything but pack wont start. Error: Uncaught Fatal Exception code 1

**Comment by zontreck** [comment]
It appears that the site hosting forge, uses Let's Encrypt.  Various other services have been impacted due to one of the CA's root certificates expiring as of 9/30/2021. I don't think there is a workaround, forge is gonna have to update their host's certificates

<img width="285" alt="xbvJWFZnNf" src="https://user-images.githubusercontent.com/1643882/135708953-ca6aee2b-8f23-4565-9b63-560934e3bd15.png">

**Comment by Eskaan** [comment]
Fixed in the latest beta: v1.1.15-beta.5

**Comment by Eskaan** [comment]
Duplicate of #1086
