### ISSUE TITLE
The forge doen't work 

### ISSUE THREAD

**Issue by Pedro36572** [killpowa/Twickt-Launcher#1123]
Forge can't download 
Screenshot:
![image](https://user-images.githubusercontent.com/92762152/137816689-7a2760d7-21fc-4d21-b811-df8050733493.png)
My OS is Debian 11 i did sudo apt dist-upgrade and sudo apt upgrade it is the stable release not bookworm or sid, 
did everything right allowed the  .appimage to be opened as an executable and tried to install better minecraft forge and it didn't work it was stuck on "downloading forge installer" fabric works but forge doesn't

**Comment by IsXGeo** [comment]
I have this same issue, fresh install of GDLauncher. Except im on Windows. It downloads forge forever at 0 percent, and if you restart the launcher it shows it as completed downloading except that it cannot be launched.

**Edit: It seems this is already fixed in one of the beta versions of GDLauncher, to anyone experiencing similar problems, consider trying a beta version.**

**Comment by Eskaan** [comment]
Duplicate of #1086
