### ISSUE TITLE
Updare All Mods button missing in 1.1.16 Beta 1

### ISSUE THREAD

**Issue by PhweeDev** [killpowa/Twickt-Launcher#1174]
When going under Manage - Mods - Check for Updates (Click the three dots) And no Update All Mods button will load. I updated to Java 17 like they asked. and there's no button there. I'm on Windows 10.

**Comment by Peca21** [comment]
Can confirm #1173

**Comment by Archilyte** [comment]
This is also happening to me

**Comment by PhweeDev** [comment]
Still missing in 1..1.16 Beta 3.

**Comment by kreezxil** [comment]
confirmed
![image](https://user-images.githubusercontent.com/3880072/143897037-96765d66-f1a8-4564-89b5-1cb7f1d26d86.png)
clicking this has no **update all** in it

**Comment by Archilyte** [comment]
> Still missing in 1..1.16 Beta 3.

you should update the title

**Comment by Corvus20** [comment]
Having this issue as well.

**Comment by kreezxil** [comment]
# The Best Workaround Yet

Everyone here experiencing problems, the best workaround is this.

If you haven't already, change to stable 1.1.15 as this will help solve your Minecraft 1.18 issue/problems.

## Now to make 1.1.15 behave properly for 1.18 aka 1.16.5+

1. click the master gear (upper right on the title bar)
1. select java on the right
1. on the right, move the slider so the paths appear
1. change the java 16 path to point to your java 17 path, 
    - if you don't have java 17 goto https://adoptium.net/
1. Profit


## **﻿Why it works﻿**
As it turns out 1.16.5 runs happily on Java 17, so by changing that one line you're now compatible with 1.16.5, 1.17.1, and now 1.18.
﻿
## **﻿Why 1.1.16﻿** doesn't work
The beta was only meant to find community acceptable placements for additional adds, it may have had other code put in place to resolve edge case issues. However, in doing so, something got effed along the way.

![image](https://user-images.githubusercontent.com/3880072/145250836-caa08bb6-ed7d-407a-8ebf-624840d195c6.png)

![image](https://user-images.githubusercontent.com/3880072/145250883-178a1c9b-9737-4ce3-9cea-522a2a48a551.png)

**Comment by Eskaan** [comment]
Fixed in v1.1.17+ d58a46d60d118997108a5540cfc88685ba6b19b3
