### ISSUE TITLE
Mod search has no results for 1.18 instances

### ISSUE THREAD

**Issue by niraqw** [killpowa/Twickt-Launcher#1187]
1.18 instances for both Fabric and Forge show no results when clicking on `Add Mod`, only showing "No mods has been found with the current filters." Additionally, clicking on a manually added mod will just show "No Data" for mods with 1.18 releases on Curseforge.

Instances with older versions of the game (1.17 and below) show search results as expected.

Example (manually downloaded the mod and added to the folder):
![image](https://user-images.githubusercontent.com/22210045/144187197-1e2c2754-c7de-4830-94f2-966ffc9d1f8d.png)

![image](https://user-images.githubusercontent.com/22210045/144187216-9cf7ab5c-a38f-4652-9e7f-84a6ae1ed5ca.png)

- OS: Windows 10

**Comment by cryolithic** [comment]
Same here. Tried switching both curse and gd launcher to beta streams, same result.

**Comment by wolrah** [comment]
I was having the same problem a few days ago but I just tried it a few minutes ago and was able to successfully download a bunch of mods in to a Fabric 1.18 instance.  From a quick skim of the source I have a moderate suspicion there was a problem affecting the service pointed to by GDL_SERVE_API which has been fixed in the last few hours.

**Comment by niraqw** [comment]
It seems that the issue has been fixed for both Forge and Fabric instances. I'll go ahead and close the issue.
