### ISSUE TITLE
Add Log4J Security issue

### ISSUE THREAD

**Issue by MG8853** [killpowa/Twickt-Launcher#1200]
**Is your feature request related to a problem? Please describe.**
Forcibly enforce the arguments related to log4j when starting all instances.
すべてのインスタンス起動時にlog4jに関する引数を強制してください。

**Describe the solution you'd like**
All
全て

**Describe alternatives you've considered**
Please add [ -Dlog4j2.formatMsgNoLookups=true ]

**Additional context**
![Inkedbd81c96b3b4e86a5f206f4a8626d7f38](https://user-images.githubusercontent.com/29114790/145578530-b7d57c64-fa84-4091-9d6e-91946a1d1f73.jpg)

**Comment by Eskaan** [comment]
Fixed in e2cfde4eb21891e092199cd10f66a11a1d61a3ba (You cant see it, but we add this to the launch arguments)
Thanks for reporting :)

Edit: whit an upgrade to a version of the launcher over or to v1.1.16 you will get the patch

**Comment by minus1over12** [comment]
A conversation in [MultiMC](https://github.com/MultiMC/Launcher/issues/4323#issuecomment-991043499) mentioned that the launch arguments change only fixes 1.16+, a different solution is needed for other versions.

**Comment by Sheape** [comment]
That is true, the fix is only for 1.17. I think the xml files provided by mojang should be placed in the config directory under your instance. If not then you could still pass in the full path to that file.
![image](https://user-images.githubusercontent.com/86521166/145666049-09e384f3-4fed-4eb4-8274-655a07d7ff57.png)

**Comment by blarfoon** [comment]
This issue is now fully fixed for GDL 1.18
