### ISSUE TITLE
Attempted to Update a 1.18 Fabric Modpack, which resulted in it being stuck on "Downloading Mods 0%"

### ISSUE THREAD

**Issue by DwarfDolphin** [killpowa/Twickt-Launcher#1202]
**Describe the bug**
I was attempting to update a modpack for Fabric 1.18, and it got stuck on the Downloading mod 0% part. I then deleted the modpack and reinstalled, with the same thing happening. The modpack specifically is Benchmark II, if that is important. 

**To Reproduce**
1. Attempt to Update or Install a Fabric 1.18 modpack
2. Watch it complete the first few steps quickly, only to get stuck on the installing mods part.
3. Wait painfully, before giving up and just closing GDLauncher

**Expected behavior**
I expected the Modpack to update as it always has, same with installing. It should install the mods during the process.

**Possible solutions**
I do not know, as I have no knowledge of code.

**Screenshots**
![image](https://user-images.githubusercontent.com/95934404/145619908-ca4edb0f-56eb-4517-8cce-fa4b94209e45.png)

**Operating System:**
- OS: Windows
- Version: 10
- Java Version: Presumably 17
- Minecraft Version: 1.18
- Mod Loader: Fabric

**Additional context**
I can still install mods manually, it is only a problem during the modpack installation.

**Comment by Evolution0** [comment]
Also happening on 1.17.1 packs like All Of Fabric 4, another user reported the same for AOF3 and AOF5. Everything else downloads fine, just not the mods.

Edit: Got word that CurseForge was down a bit ago and may have something to do with that, might just be a wait and see situation as everything spools back up.

**Comment by internet-person** [comment]
having this happen on benchmark 2 with a bunch of my buddies aswell.

**Comment by WolfBV** [comment]
gdlauncher version? How long did you wait before closing gdlauncher?

**Comment by tilda** [comment]
have had this situation today as well, dug a little into it, here's my findings.

there seems to be some cases where the curseforge api currently used will error with 504 (gateway timeout). (note: the api.gdlauncher.com request is unrelated but also interests me as well - but it is offtopic for this issue)

![](https://cdn.discordapp.com/attachments/710161667765567556/922234445258453042/unknown.png)

in those cases gdlauncher *will* get the rest of the download links it seems but doesn't progress due to the few errored requests.

so my hunch is that there just needs to be a auto-retry function implemented for downloading modpacks in case of things like this - probably with exponential backoff as well to avoid tripping any ratelimits.

**Comment by TheButterbrotMan** [comment]
Experiencing the same problem

**Comment by NicTanghe** [comment]
I also have the same problem.

I Dl`ds using winget.

**Comment by Tradonix** [comment]
Yup, had the same issue. 504 as tilda said. 

For anyone getting this:
restart the download (download the pack again, repair instance, switch version) a few times and it will eventually work.

**Comment by Eskaan** [comment]
Yeah, it will eventually work. Leave it some time, it will be better later. (504 is a Timeout.)
Also you don't have to tell us that you have the problem too, just go make an upvote on the question.
There is a reason why it's pinned. Also a Duplicate of #1154.
