### ISSUE TITLE
Stuck Downloading Mods at 0%

### ISSUE THREAD

**Issue by fredooda** [killpowa/Twickt-Launcher#1266]
**Describe the bug**
The modpack I want to download is stuck at 0% mod downloading and wont move.

**To Reproduce**
1. Go to download a mod
2. See error

**Expected behavior**
Not downloading

**Possible solutions**
Some ideas of how you would solve this issue, if possible

**Screenshots**

**Operating System:**
- OS: [e.g. Windows]
- Version: [e.g. 10]
- Java Version: [e.g. 8/16]
- Minecraft Version: [e.g. 1.16.5]
- Mod Loader: [e.g. Forge/Fabric]

**Additional context**

**Comment by Uchiwars** [comment]
me too for the past months so i just gave up and went for another one

**Comment by landretk** [comment]
The new API hangs almost every time unless you catch it when it's not busy. Gdevs please revert to using forgesvc

**Comment by DrUltraLux** [comment]
If you close the launcher, repair the modpack over and over, eventually it works.

**Comment by Darianna77** [comment]
Same problem for me. Sometimes it works when i start the launcher as a admin. But sometimers it dont help :/

**Comment by Midnex** [comment]
Been having this issue for days along with the issue that doesn't remove old mod versions, and now it won't reinstall anything even on fresh downloads. Whatever dev did, is has completely broken GDLauncher.

**Comment by hammackj** [comment]
Interesting the Ads work but the program does not. 5 days since this ticket was open is the project dead?

**Comment by huantianad** [comment]
@hammackj it is not in fact dead; you guys are just on an issue that's a duplicate of a pinned issue #1154. It's not that hard people.

Besides the launcher being broken is entirely Curseforge'a fault. Why would ads be broken.

**Comment by Eskaan** [comment]
No it's not. Come over on our Discord Server if you want, there you will see all activity on the project if you want too.
Also to everyone watching this issue, there is a build out in development that you can test if you want. Maybe reporting that it all works will help bringing it out to the community faster. But be aware, there are reasons we dont push these build to beta, so don't complain if something is not working. Also I think the Autoupdater is turned off on these builds.

**Use at your own risk and don't complain:**
Here is the (at this moment) latest dev build: https://github.com/gorilla-devs/GDLauncher/actions/runs/1766043701
Which should include the fix for this issue.

**Comment by Eskaan** [comment]
Also hopefully one day Ads get broken but who knows ;)

**Comment by blarfoon** [comment]
Ads work because they are simple images, anyway I don't see how they are related to the issue. The launcher itself is a complex system that depends on a multitude of services that often fail (like in this case). Curseforge is in charge of their APIs and we simply query them. If they don't work there is nothing we can do. Moreover, this is an open-source project and I don't get paid for it. As soon as someone will start paying me a full-time salary for it I'll be more than happy to promptly fix any issue, until then, I'll just work on it when I feel like it. This is how a free and open-source side project works.
If you really need it fixed, the code is public and you can contribute to it as well...

**Comment by Eskaan** [comment]
Also Duplicate of #1154

**Comment by tiago4171** [comment]
> No it's not. Come over on our Discord Server if you want, there you will see all activity on the project if you want too. Also to everyone watching this issue, there is a build out in development that you can test if you want. Maybe reporting that it all works will help bringing it out to the community faster. But be aware, there are reasons we dont push these build to beta, so don't complain if something is not working. Also I think the Autoupdater is turned off on these builds.
> 
> **Use at your own risk and don't complain:** Here is the (at this moment) latest dev build: https://github.com/gorilla-devs/GDLauncher/actions/runs/1766043701 Which should include the fix for this issue.

This workarround fixed my issue! I've downloaded two modpacks from curseforge platform without a single error on GDLauncher logs. Nice, now I can use GDLauncher again! Yay!!

**Comment by Eskaan** [comment]
Thanks for telling us 👍

**Comment by Yasamashi** [comment]
Same to me, I downloaded the "fix" installation and, while it isn't a 100% fix meaning it will fail the download for some time, at least you can "Retry" or "Cancel" which is a lot less tedious than Right click > Open Folder > Delete > Close GDL > Re-open GDL > Search the modpack > Give it a name > Pray to whatever you believe on it works. I think it can depend on the modpack too? I didn't have any problem downloading one but I couldn't for the life of me download another.
