### ISSUE TITLE
Update all mods causes compatibility issues

### ISSUE THREAD

**Issue by Face4time** [killpowa/Twickt-Launcher#1269]
TO REPRODUCE
1. open gdlauncher
2. right click on rlcraft
3. select manage
4. Click on mods
5. then click on update
6. when update (in my instance) dynamic surroundings
7. when the game launches the error should appear

Expected behavior
it will tell you what you already have another version of the mod installed.
![Skærmbillede (5)](https://user-images.githubusercontent.com/81111336/151617295-13824174-fffd-4613-bf56-58cd49773c91.png)

Possible solutions
0

- OS WINDOWS 10
- Version: 21H2
- Java Version: 8 update 321
- Minecraft Version: 1.12.2
- Mod Loader: 1.12.2 - 14.23.5.2860

**Comment by camperboy1000** [comment]
This is not an issue with GDLauncher but an issue with mod compatibility.

Modpack authors carefully select which versions to use in their pack in order to avoid these compatibility issues. By individually updating mods, you are introducing the possibility of these issues arising. Please refrain from updating mods individually and use the "modpack" tab to update the pack whenever there is an update.

**Comment by Eskaan** [comment]
ALL CAPS btw
