### ISSUE TITLE
Certain mods can't be found on "New Mod" menu. 

### ISSUE THREAD

**Issue by ItsNovaAndCrap** [killpowa/Twickt-Launcher#1272]
**Describe the bug**
This bug isn't that bad, although I am trying to make a test instance for a mod I'm making called Stonepatch, I can't find the mod in the "New Mod" feature; even notice it's online on CurseForge as an Alpha.

P.S. I have tried changing the mod release channel, by the way. Didn't work.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a Forge 36.2.23 instance
2. Go to the "Mods" tab in instance settings once finished patching Forge.
3. Click "New Mod" and search for "Stonepatch".

**Expected behaviour**
Stonepatch shows up and I add it to my instance's mod list.

**Operating System:**
- OS: Windows 10
- Version: 1.1.21
- Java Version: 8u321
- Minecraft Version: 1.16.5
- Mod Loader: Forge

**Comment by ItsNovaAndCrap** [comment]
By the way, here's the link to my mod: [Stonepatch Mod](https://sites.google.com/view/itsnova/mcmods/stonepatch/downloads)

**Comment by AshtakaOOf** [comment]
so this mods isn't even on curseforge

**Comment by commandhat** [comment]
![image](https://user-images.githubusercontent.com/3821018/154330301-624aadbc-2f04-42fe-a434-4d39e550420b.png)

**Comment by ItsNovaAndCrap** [comment]
Have you even checked out the downloads for Stonepatch?

**Comment by commandhat** [comment]
> Have you even checked out the downloads for Stonepatch?

I tried to find it the same way GDLauncher does (look for a mod listing literally titled "Stonepatch" on curseforge), and couldn't. That's what the picture is about.

The link you provided is for a Google Sites page, which is not Curseforge and therefore does not show up on GDLauncher because it does not show up on Curseforge.

Edit: I now see that the downloads button takes you to a Curseforge listing. Maybe you don't have the project set to be publicly viewable?

-----

Looks like projects aren't publically viewable unless they have at least one release file within the last two years. This is the same problem that a handful of other mods run into due to being considered "abandoned", which delists them. A contributor will probably need to pick one bug to merge issues into:

#1272 (this one)
#1278
#1223 (probably the best base, as this one lists more affected mods.)

-----

Unfortunately this looks like it's not a GDLauncher issue, as if GDlauncher suffers the same problem then according to behavior, so does the official CurseForge launcher.

A workaround for now is to download the mods yourself although it's obviously very much not ideal. Maybe a contributor could add a dialog that warns of unlisted mods? Should be simple enough to test, in theory, since unlisted mods don't show up in listings.

**Comment by commandhat** [comment]
Add #1274 to the dupes list.

**Comment by commandhat** [comment]
Been away for a bit, but #1301 is another dupe.

**Comment by commandhat** [comment]
This is literally why Github has a search bar denoted with a magnifying glass.
#1299
#1323
