### ISSUE TITLE
CF API proxy returns a 404 for xali's Enhanced Biomes: River & Pond

### ISSUE THREAD

**Issue by chase** [killpowa/Twickt-Launcher#1274]
**Describe the bug**
When attempting to download this mod from the [Valhelsia Enhanced Vanilla modpack](https://www.curseforge.com/minecraft/modpacks/valhelsia-enhanced-vanilla/files/3634445) it returns a 404

This is the URL that it attempts to access:

https://api.gdlauncher.com/cf/mods/534154/files/3566820

**To Reproduce**
1. Use the latest build at https://github.com/gorilla-devs/GDLauncher/actions/runs/1766043701
2. Open the dev console
2. Search for and install Valhelsia Enhanced Vanilla version 1.07 for 1.18.1
3. Wait for the 404

**Expected behavior**
The download completes for the following file: https://www.curseforge.com/minecraft/texture-packs/xalis-enhanced-biomes-river-pond/files/3566820

**Possible solutions**
Optionally allow the user to manually download the mod's zip and install that if the API fails.

**Screenshots**
N/A

**Operating System:**
- OS: Pop!_OS (Linux)
- Version: 21.10
- Java Version: 16
- Minecraft Version: 1.18.1
- Mod Loader: Fabric

**Additional context**
Modifying the modpack and removing the above mod then causes a 404 for this mod:
https://www.curseforge.com/minecraft/texture-packs/xalis-enhanced-vanilla/files/3571044

Maybe this has to do with the fact that on [the files tab, these are listed under the additional files section?](https://www.curseforge.com/minecraft/texture-packs/xalis-enhanced-vanilla/files)

**Comment by AshtakaOOf** [comment]
can you try the latest beta ?

**Comment by andOrlando** [comment]
> can you try the latest beta ?

I had a similar issue when trying to download seaopolis (mods stuck at zero, api calls were returning 400, 404 and 504) but with the beta the requests go through

**Comment by Vaelzan** [comment]
> can you try the latest beta ?

In this case the latest beta won't (and doesn't - I've tried it) help, since this is a separate issue to the intermittent issues with the API that people have been having. Just take a look directly at this URL that is being requested (different file to the OP's first example, but same reason for triggering the issue):

https://api.gdlauncher.com/cf/mods/513425/files/3571044

As you can see, it returns a 404 error every single time - as does requesting any Resource Pack file that is under the _Additional Files_ section of the Resource Pack on the CurseForge website (as noted by the OP). It's 100% reproducible.

Edit: The OP referred to the files having trouble as mods, but these are both resource packs rather than mods, and are the only two in the mentioned modpack that are set as _Additional Files_. Image attached for additional clarity as to what I mean - GDLauncher can install the top file there but not the bottom file.
![image](https://user-images.githubusercontent.com/6418846/154051490-956a674b-f865-4356-89a6-9a3262271735.png)

**Comment by Vaelzan** [comment]
Just to add some further context that I've just learned, this is something that has been confirmed by wolfgang from Overwolf as being at least partially an issue on their end (although frustratingly, it doesn't impact the CurseForge app itself, just third parties that use their API). They've put in a feature request but no idea if / how long it'd take to fix.

**Comment by ProxyPlayerHD** [comment]
oh i was about to open a new issue for this since i've also been having problems installing new packs as well.
modern packs just get stuck at "downloading mods 0%" with 400, and 504 errors.
and old packs like FTB Ultimate are in a constant cycle of "Downloading game files 0-100%" and "Injecting Forge 0-50%". the log is just filling up with endless waves of 404 errors.
and i did try both the newest beta and stable release (1.1.21-beta) and (1.1.21)

but it has been like 2 weeks since the last post on here and it's still not fixed on their end?

**Comment by tomwolfgang** [comment]
@Vaelzan the reason it is working with the CF app itself is that we use the https://docs.curseforge.com/#get-files API - which doesn't filter out additional files

**Comment by Eskaan** [comment]
Duplicate of #1223

**Comment by Vaelzan** [comment]
> Duplicate of #1223

I do not believe this issue to be a duplicate of the linked issue, and I believe @commandhat in #1330 also mistakenly called this safe to close despite being unrelated to the issue they created. The files here are *NOT* considered abandoned by CurseForge (based on the criteria mentioned in #1330), they're relatively recently uploaded resource packs that are marked as "Additional Files".

Additionally, since last commenting on this issue it appears that GDLauncher has actually regressed in the handling of resource packs, incorrectly placing *all* resource packs into the mods folder instead of the resource packs folder.

I attempted to reproduce it again just now to see if anything has changed since the last time I tested it, but the pack now simply silently fails to download with no feedback at all to the end user. Even with CurseForge's API changes I can't really fathom why errors during installation are just being silently discarded by GDLauncher instead of displayed. I can only even see that a couple of 404 errors have occurred because I'm familiar enough to use the console to take a look, but the average user won't know to look there.

**Comment by Eskaan** [comment]
We don‘t support Resource Packs anyways, they shouldn‘t even appear in the „Mod Browser“.
The 404 errors most likely occur because the mod has disabled third party api programs. You are right, it is not exactly a duplicate of this issue. More likely #1342. This is just the older symptom of this. In any way its a external issue of CurseForge so it dosen‘t even need to be a duplicate to be closed, sadly we can’t do anything for it.

**Comment by Vaelzan** [comment]
> We don‘t support Resource Packs anyways, they shouldn‘t even appear in the „Mod Browser“. 

They don't appear in the Mod Browser (and nobody claimed that they did), these are Resource Packs included by a Modpack... and Resource Packs included in Modpacks worked just fine earlier in the year (except for ones marked as Additional Files). Thus why I say this has regressed - earlier functionality that used to work is now broken. If the official stance is that GDLauncher won't support Resource Packs *at all*, then it's going to keep installing partially-broken Modpacks in situations where they're including Resource Packs, which is just going to cause confusion amongst players who wonder why their installation looks completely different to that of people using any other launcher. I would honestly prefer packs to be unavailable rather than installed in a partially-broken state.

> The 404 errors most likely occur because the mod has disabled third party api programs. 

Yes, my most recent test had some issues because of blocked third party downloads, but not when this issue was first created. Those earlier 404 errors were happening long before that was even a setting that could be toggled.

> You are right, it is not exactly a duplicate of this issue. More likely #1342. This is just the older symptom of this. In any way its a external issue of CurseForge so it dosen‘t even need to be a duplicate to be closed, sadly we can’t do anything for it.

#1342 relates to mods marked as blocking third parties, which is a separate issue entirely (other than my recent paragraph, which was purely an aside commenting on how they are silently ignored without feedback to the user). 

I might even believe this was an external problem if other third party launchers had the same problem, but this appears to be exclusive to GDLauncher. I'm not even sure how CurseForge could possibly be blamed for the part where GDLauncher now puts resource packs into the mods folder (which again, used to work), and for the other part relating to mods / resource packs marked as "Additional Files", somebody from Overwolf (tomwolfgang) already responded above explaining that, when they implied that using that API would resolve the issue.

Given that response above, marking this as an External Issue is simply disingenuous from my perspective.

**Comment by Eskaan** [comment]
Okay okay. I will check it in detail.
