### ISSUE TITLE
Instance gone after trying to update forge

### ISSUE THREAD

**Issue by KyBeeS** [killpowa/Twickt-Launcher#1298]
When trying to update the the latest version of forge for 1.16.5, I got an error that access was denied for removing the files, so i cancelled the download and the instance disappeared entirely. The folder is now completely empty and my pack is completely gone

**Comment by matthewd** [comment]
This just happened to me too: while attempting to update a modpack version, it hit an access denied error for a dll. I chose "Cancel Download", intending to restart, and it turns out that button eats the instance: https://github.com/gorilla-devs/GDLauncher/blob/3d6723468790124811aebabc6745854fa5216074/src/common/modals/InstanceDownloadFailed.js#L29 ... saves, backups, and all.

That's obviously reasonable during an initial download/install, but during an upgrade, it is Not A Great Result.

**Comment by Eskaan** [comment]
Duplicate of #1288
