### ISSUE TITLE
Error: It looks like you didn't buy the game.

### ISSUE THREAD

**Issue by ghost** [killpowa/Twickt-Launcher#1333]
**Describe the bug**
'Error: It looks like you didn't buy the game.' appears when signing in with Microsoft. 

**To Reproduce**
1. Start GDLauncher.
2. Click on 'Sign in with Microsoft'.
3. Do all the required signing in steps properly.
4. See the error 'It looks like you didn't buy the game.'

**Expected behavior**
The launcher should log in.

**Possible solutions**
I've read somewhere that if you logged in in the 3rd party launcher while having minecraft open from the official launcher, it would detect that you own the game. But this hasn't worked so far.

**Screenshots**

![image](https://user-images.githubusercontent.com/49818346/167958687-ad261474-b02b-4e49-9dec-bb5b7a5be594.png)

**Operating System:**
- OS: Windows
- Version: 10
- Java Version: 18
- Minecraft Version: 1.18.2
- Mod Loader: Fabric

**Additional context**
I have tried signing in several times with different methods, and made sure I was 100% not confusing between the old Mojang and Microsoft migrated emails. I bought Java edition back in 2016, and it works perfectly on the official launcher, but in the minecraft.net store, it appears **Buy Now** on the Java Edition section. So that might be related in any way. _(Of course, I did migrate the account months ago, also I'm sure i have the Java Edition, and not any other.)_
I also contacted support from Minecraft and they told me they can't help with third party applications.

**Comment by ghost** [comment]
If anyone encounters themselves on the same issue, make sure to check if theres any other possible emails attached to your Minecraft account! Somehow, I used an email that was registered but without having owned Minecraft.

**Comment by manshizofrenia** [comment]
i have the same problem, but i do own minecraft java edition on that email. i use a steam deck. even fresh installation did not fix the issue

**Comment by EsbenHojris** [comment]
I had this same issue, and it seemed to fix itself when I launched the Java edition of Minecraft in the official launcher, since it asked me for a handle (username or whatever, something like that) to assign to my account.

I feel like this helps others, especially since I hadn't played Minecraft for a long time and I suspect that is why it gave me this error.

**Comment by manshizofrenia** [comment]
yes it fixed it self somehow

**Comment by manshizofrenia** [comment]
it is really frustrating why i can not use the launcher without an internet
connection and when back online i need to sign in again and then can not
even do that. it still shows sometimes that i did not buy the game. there
is no way to fix this too. it is annoying to retype my login info again and
again on another level because i am using a steam deck for it.

i have a suggestion to have a toggle to never having to login a second
time. why would you need to anyway? do you really have to check if i own
the game once a week?

**Comment by siqNezz1337** [comment]
this issue appeared several times to me by now, usually when i wasnt playing for a few days. using the other connected email didnt work but once i logged in on the official minecraft-website (login with a microsoft account) i was able to login with the gd-launcher. maybe this information helps someone.
