### ISSUE TITLE
Inapp browser mod downloading stopped by Cloudflare

### ISSUE THREAD

**Issue by HagiaHaya** [killpowa/Twickt-Launcher#1367]
**Describe the bug**
As of new version came out there is an in-game webview that downloads mods. After downloading a few modpacks I got stuck in the Cloudflare window and I can't move on. Tried both clicking it by hand and waiting so the launcher would do things for me - no success.

**To Reproduce**
1. Download modpack from Curseforge
2. Wait till opted mods come out and try to download them

**Expected behavior**
Let me solve the captcha or try to bypass it.

**Possible solutions**
I can see that launcher waits 5 seconds to let the mod download but it is also resetting the captcha. Maybe if it detects Cloudflare IP, then the launcher should stop the timer so a person could click and solve the puzzle?

**Screenshots**
![image](https://user-images.githubusercontent.com/26824260/174062455-e0b04751-730e-452b-b5f1-504e336a94d5.png)
![image](https://user-images.githubusercontent.com/26824260/174062489-4a1715bc-e88d-4bf3-86bb-aeb68a848e0c.png)
![image](https://user-images.githubusercontent.com/26824260/174063103-17677516-57a8-4d1e-b044-d2688bb30ef1.png)

**Operating System:**
- OS: Windows 11
- Version: 1.1.24
- Java Version: 8/17
- Minecraft Version: 1.18.2
- Mod Loader: Fabric

**Comment by Eskaan** [comment]
A known issue, we merged and released anyways

**Comment by Aliervo** [comment]
I have a few thoughts on how to fix this, are there any packs that consistently trigger the cloudflare captcha for me to test against?

Also, as a sanity check, the relevant functions should be the ones triggered by `ipcMain.handle('download-optedout-mod(s),...`, correct?

**Comment by ProjectSynchro** [comment]
Perhaps making use of similar methods as FlareSolverr could be handy:
https://github.com/FlareSolverr/FlareSolverr

**Comment by tanchevk** [comment]
Maybe try detecting Cloudflare and temporarily disable the timeout if the Cloudflare page is open?

**Comment by ranenvious** [comment]
any updates on this? This basically makes using GDlauncher impossible since so many mods trigger the external download window. (at least for me, maybe for others it's different but the main reason I use GDLauncher is because it lets me find and download lots of mods quickly for custom packs for me and some friends)

**Comment by miuirussia** [comment]
Any news?

**Comment by Eskaan** [comment]
Issue open, no new messages or references. I do not think so.
There are a few methods to retry like changing your IP or just waiting to fix it.

**Comment by JoelYoung01** [comment]
Also been having this issue recently, pretty inconsistent though.

**Comment by cyraid** [comment]
One option could be to provide a manual option, which shows the 3rd party mods in a list, and download links, then hitting done when done.

**Comment by Rezaldy** [comment]
I.. Don't understand.

> A known issue, we merged and released anyways

Does this mean "We know it's a problem, we don't have a manual workaround, we just released it as is anyways"? Am I not able to download the mods manually and put them in a certain folder? Because this "Yes but no" approach just sounds a bit silly because it's forcing me to move to a different launcher "until further notice" when that was exactly what I was trying to avoid. 

I agree with @cyraid; Automation of those downloads is one of the greatest QoL features, but shouldn't just be the only option available for us users in cases like these where something that's out of the hands of the GD developers happens that requires time to fix it.

**Comment by Eskaan** [comment]
At the time we implemented this workaround, it was more a concern to bring the fix out to users. But as this project barely receives any contributions, no one implemented a "real" manual download yet. There just came a pr about this I am going to review today (#1512) btw.

**Comment by tanchevk** [comment]
Realistically, downloading mods manually and shoving them in `mods`, while
viable for the meantime, is not pretty. The developers know of the issue
but decided to publish the update sooner rather than fixing this because
the overall curseforge API changes were more important than fixing a small
issue (imagine the pandemonium if they had decided to fix this before
releasing the curseforge API bypass) so as to provide more up to date
features. Bugs like this one, although inhibiting the launchers ease of
use, are not critical and as such can be addressed at a later date when
other, more critical issues are resolved.

**Comment by Rezaldy** [comment]
@Theboiboi8 I agree, it's not pretty, but when the "pretty" option is not available, **some other option should be**, as unsanitary as it may be so the issue does not become blocking for the user experience and have them move to options more viable to them when GDLauncher was supposed to solve that problem for them.

I read the proposed PR that @Eskaan just mentioned and it is what another launcher I had to download has already been doing, which is why I was wondering if GD refused to implement this or if more played into this (The latter being none of my business). I'm glad this change is being made though.

FYI; The other launcher just asks me to open the URLs of blocking mods that immediately download the correct file when clicking the "open in browser" button, and then place it in my Downloads folder. It automatically checks my user's Downloads folder every x seconds for the files' presence and continues when everything has been downloaded. Seems like this is pretty much what the PR proposes.

Thank you for the update @Eskaan and thanks for the PR @Celeo (#1512)!

**Comment by NyarlathotepZERO** [comment]
Give users the option of downloading manually to get around this. Even if it automates the link loading process, but then becomes "hands off" once the link for each of the mods has been clicked one by one.

**Comment by ray73864** [comment]
I have a PiHole set up which points to Cloudflare DNSSEC servers, noticed when I went to install 'All The Mods 8' today that for every mod it has to open the inapp browser for, it gets the usual 'www.curseforge.com needs to review the security of your connection before proceeding'.

I don't get any captchas that I have to fill out (Though I did ever once in a while notice a "Verify you are human" blue button, can't click it quickly enough though), but once all the popups have finished, GDLauncher just comes up telling me they all failed to download.

I realise that some modmakers choose to go this route of not allowing the mods to be pre-included in the modpack, but yeah.

**Comment by alejandro-esquivel** [comment]
Has this been fixed? The curseforge screen keeps reloading whenever downloading some mods.

**Comment by Eskaan** [comment]
I think this label describes it enough. This issue is, in the end, 100% caused by Curseforge and their download policies.
This is only a work-around that CF blocked by setting the cloudflare settings quite high. We do our best at working around this issue but in the end we can't fully solve it at our end.

**Comment by cyraid** [comment]
All because of a setting that shouldn't have been there to begin with? Preventing from bundling the mods? Greed. (On curseforge)

**Comment by GDoe5** [comment]
> Bugs like this one, although inhibiting the launchers ease of use, are not critical and as such can be addressed at a later date when other, more critical issues are resolved.

Respectfully, I completely disagree. It doesn't inhibit the "ease of us", it makes it completely impossible to download particular modpacks. There is no "just skip this mod" or "just let me download the mod manually" - if it fails to automatically get it from Curseforge, there is no choice but to just cancel downloading the modpack. How is that not critical? It means we can't actually use GDLauncher at all? 

I love GDLauncher, but I have literally no choice but to go and use another launcher that will let me do it? That is obviously critically affecting my usage of the program.

![image](https://user-images.githubusercontent.com/12865776/215290467-88a790bf-ef4c-4760-9f3b-ff10ea709b0c.png)
Stuck whirring forever because I had to close the browser window and no option to just disable/ignore the missing mod.

**Comment by Eskaan** [comment]
I can completely agree with your disappointment, but I'm the end I can only repeat what I said already: Most of those problems don't lay by us but get introduced by Curseforge for us to fix. And this in particular was a move specifically done to prevent external mod downloading. Seems like it worked for Curseforge :/

Another problem is that our development currently concentrate on the rewrite and I am more or less the only official maintainer over here, and I can only do necessary work on GDL in my free time atm. PRs are still welcome!

By the way, the manual download and continue button has been done and is already in a beta release. I plan on moving it to stable this weekend.

**Comment by GDoe5** [comment]
> By the way, the manual download and continue button has been done and is already in a beta release. I plan on moving it to stable this weekend.

Looking forward to moving straight back to GDLauncher when that's ready! Thank you so much for your hard work, and really appreciate your response.
