### ISSUE TITLE
GDLauncher occasionally resets to default settings and makes you log in again

### ISSUE THREAD

**Issue by Nevrai** [killpowa/Twickt-Launcher#1422]
**Describe the bug**
If you’ve downloaded a mod that has third-party downloads disabled, meaning it’s downloaded via the CurseForge site within the launcher, when you close GDLauncher and open it again, you’ll be logged out of your Minecraft account and will have to log back in, and all your preferences within the launcher will be reset to their defaults. This affects the launcher’s general settings and the Java settings but not individual instance settings.

**To reproduce**
1. Download a mod that has third-party downloads disabled
2. Close GDLauncher
3. Open GDLauncher again

**Versions:**
* **GDLauncher version:** 1.1.27 (latest stable version)
* **OS:** Windows 11 Home, version 21H2

**Comment by jaredniegas** [comment]
Same here.

My Windows version is Windows 10 Pro - 21H2. My GDLauncher version is the latest stable version as well (1.1.27)

**Comment by Duckie-Dickins** [comment]
It was my understanding that this was part of the fix to avoid getting a captcha from cloudflare when attempting to download mods which were opted out by the mod creators. Cookies are wipes when downloading modpacks that contain mods which the mod creator has opted out of  third party launchers. The wiping of the cookies also wipes your session cookie for being logged into your microsoft minecraft account.....  This only happens when downloading modpacks and opted out mods. As soon as you close the launcher, you'll have to log back in the next time you open it.. If you haven't downloaded anything, the session cookie will persist and you won't be required to log back into your microsoft minecraft account....at least until you download another modpack/mod. 

I'm not sure why cookie wiping also resets things in the java section of the settings. It doesn't forget the custom location for my GDLauncher instances and such....just the java settings.

**Comment by skorpeyon** [comment]
I can only speak for myself, but on the user-friendliness side I'd much rather have to fill out a captcha when downloading a mod than have to re-login in to my Microsoft account which has both an impossible-to-remember password and 2-factor authentication on it. Re-entering that information using a password manager and grabbing my phone to approve the login, then having to fix multiple settings the following session is honestly quite a bit more annoying than clicking a few pictures or typing in some random letters for a captcha.

**Comment by Nevrai** [comment]
I can confirm that this only happens when you’ve downloaded a mod that has third-party downloads disabled, meaning you have to go through the CurseForge site within the launcher.

It wouldn’t be as big of a problem if it didn’t also reset your launcher settings, both the general settings and Java settings. But as @skorpeyon describes, it is more annoying if you have two-factor authentication enabled.

If this is an issue that can’t realistically be fixed, it would at least be nice to have the option to disable GDLauncher’s CAPTCHA-bypassing feature, making you enter a CAPTCHA each time. It would be a nice trade-off to avoid having to log back in and change your settings again each time.

**Comment by jaredniegas** [comment]
An option to opt-in to having Captchas instead would be a blessing.

**Comment by skorpeyon** [comment]
Just to add to the conversation, as I had to log in again just now, I'd forgotten to mention it also makes you go through the first-boot-style information screens each time you have to relog, which I think is even more frustrating to me than relogging and re-authorizing via 2-factor. Definitely agree with @jaredniegas, a way to opt-in to keeping the cookies and dealing with captchas would be a wonderful option.

**Comment by Ladvace** [comment]
could you try this https://github.com/gorilla-devs/GDLauncher/pull/1431 to let me verify if the problem is the cookie being wiped?

**Comment by Nevrai** [comment]
Can confirm this has been fixed in version 1.1.28. Thank you so much!

**Comment by jaredniegas** [comment]
Thanks for the fix, GDLauncher is amazing.
    On Sunday, August 28, 2022 at 07:35:37 AM GMT+8, DeleteMetaInf ***@***.***> wrote:  
 
 


Closed #1422 as completed.
