### ISSUE TITLE
modpack is not loading

### ISSUE THREAD

**Issue by Hammodh** [killpowa/Twickt-Launcher#1525]
I have made a minecraft modpack using curse forge and i am trying to import it after zipping and its not importing it just keeps in the loading screeb

**Comment by Eskaan** [comment]
I'll do the same effort as you now and just close this as a dup because I expect it to. If you want to report an issue,
1. Check for (potentially closed) issues covering your case.
2. Check that you are on the newest version of the software,
3. Use the bug report form and follow the steps described there.
