### ISSUE TITLE
Why the "clean commit"?

### ISSUE THREAD

**Issue by b1ek** [killpowa/Twickt-Launcher#1597]
I just don't understand why this is done. IMO this detroys the whole idea of having the code stored in a VCS.

**Comment by Eskaan** [comment]
I think it was to make the repo smaller. It wasn’t my idea but I wasn’t strictly against it either (It was about 0.5G or something at that point).

If you want, I should be able to reconstruct most of the history based on my local copy.

**Comment by Eskaan** [comment]
I was able to reconstruct all of the commit history and pushed the [`master_legacy`](https://github.com/gorilla-devs/GDLauncher/tree/master_legacy) branch. Sadly, the commit times are lost due to the rebase. You will have to look at the master branch to get those.

Edit: I just found the rebase option to keep the dates, so now the old history is fully restored.
